import type { NextPage } from "next"
import Head from "next/head"
import Layouts from "../components/Layouts"

const Home: NextPage = () => {
  return (
    <div className="grid font-Poppins  justify-center">
      <Head>
        <title>Creative Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Layouts />
    </div>
  )
}

export default Home
